In [2]:
from sklearn.datasets import load_digits, load_iris
import numpy as np

In [3]:
iris = load_iris()
iris_data = iris.data
iris_targets = iris.target

In [4]:
data = iris_data[:,:2]
targets = (iris_targets != 0) * 1

In [309]:
data.shape

(150, 2)

In [310]:
input_nodes = 2
hidden_nodes = 2
output_nodes = 1

weights_i_h = np.random.rand(input_nodes,hidden_nodes)
weights_h_o = np.random.rand(hidden_nodes, output_nodes)

In [258]:
weights_h_o

array([[0.80626896, 0.03171838, 0.04686951],
       [0.71924688, 0.20100928, 0.37247972]])

In [313]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [314]:
def feed_forward(x):
    hidden_output = sigmoid(np.dot(x,weights_i_h))
    final_output = np.dot(hidden_output, weights_h_o)
    
    return hidden_output, final_output

In [315]:
def back_prop(hidden_output, final_output, y, x, weights_h_o, weights_i_h):
    # error at final node
    error = y-final_output 
    # print(error)
    # hidden layer contribution to error
    hidden_error = np.dot(weights_h_o,error)
    
    weights_h_o += error * 0.01 * hidden_output[:, None] # y-y^ * X
     
    weights_i_h += hidden_error * hidden_output * (1-hidden_output) * 0.01 * x[:, None]
    

In [316]:
for i in range(100):
    for x,y in zip(data, targets):

        # feed forward
        hidden_output, final_output = feed_forward(x)
        back_prop(hidden_output, final_output,y, x, weights_h_o, weights_i_h)

In [317]:
for x,y in zip(data, targets):
    hidden_output, final_output = feed_forward(x)
    print(final_output)

[0.88949465]
[0.88330713]
[0.88019678]
[0.87741597]
[0.8880767]
[0.8958913]
[0.87909451]
[0.88723277]
[0.87135522]
[0.88384113]
[0.89526381]
[0.88331584]
[0.88122086]
[0.86954117]
[0.90185026]
[0.90146697]
[0.8958913]
[0.88949465]
[0.8999881]
[0.89063506]
[0.89422481]
[0.89026992]
[0.88010091]
[0.88865329]
[0.88331584]
[0.88531584]
[0.88723277]
[0.89125729]
[0.89086326]
[0.88019678]
[0.88177913]
[0.89422481]
[0.89331999]
[0.89822448]
[0.88384113]
[0.88631548]
[0.89615469]
[0.88619327]
[0.87205173]
[0.88908272]
[0.88766339]
[0.86909695]
[0.87335536]
[0.88766339]
[0.89063506]
[0.88122086]
[0.89063506]
[0.87799976]
[0.89366291]
[0.88678383]
[0.91295896]
[0.90708102]
[0.91187157]
[0.8908436]
[0.90710505]
[0.89660297]
[0.90621289]
[0.87954329]
[0.90846212]
[0.88757775]
[0.87868875]
[0.90028263]
[0.89843722]
[0.90261867]
[0.89546192]
[0.9099759]
[0.8958694]
[0.89770193]
[0.90127318]
[0.89363573]
[0.90094919]
[0.90227946]
[0.90377442]
[0.90227946]
[0.90626742]
[0.90872021]
[0.91023669]
[0.909

In [244]:
weights_h_o

array([[0.36474612],
       [0.5455291 ]])

In [62]:
hidden_activations = sigmoid(np.dot(X,weights_i_h))

ValueError: shapes (150,2) and (4,) not aligned: 2 (dim 1) != 4 (dim 0)

In [96]:
weights_input_to_hidden = np.random.normal(0.0, input_nodes**-0.5, 
                                       ( hidden_nodes, output_nodes))

In [97]:
weights_input_to_hidden

array([[-0.44424801],
       [-0.39118625]])

In [274]:
def MSE(y, Y):
    return np.mean((y-Y)**2)

In [311]:
from my_answers import NeuralNetwork
import sys

N_i = data.shape[1]
network = NeuralNetwork(N_i, hidden_nodes, output_nodes, 0.01)

losses = {'train':[], 'validation':[]}
for ii in range(1,100):
    # Go through a random batch of 128 records from the training data set

                             
    network.train(data, targets)
    
    # Printing out the training progress
    train_loss = MSE(network.run(data).T, targets)
    # val_loss = MSE(network.run(val_features).T, val_targets['cnt'].values)
    sys.stdout.write("\rProgress: {:2.1f}".format(100 * ii/float(100)) \
                     + "% ... Training loss: " + str(train_loss)[:5])
#     sys.stdout.flush()
    
    #losses['train'].append(train_loss)
    #losses['validation'].append(val_loss)

Progress: 99.0% ... Training loss: 0.245

In [312]:
network.run(data)

array([[0.82201952],
       [0.81926346],
       [0.81865563],
       [0.81751162],
       [0.82176971],
       [0.82421668],
       [0.81861657],
       [0.82121369],
       [0.81487117],
       [0.81963911],
       [0.82381082],
       [0.8200205 ],
       [0.81859688],
       [0.81434873],
       [0.82563093],
       [0.82593499],
       [0.82421668],
       [0.82201952],
       [0.82501414],
       [0.82275702],
       [0.82310224],
       [0.82252593],
       [0.81924995],
       [0.82144832],
       [0.8200205 ],
       [0.81988085],
       [0.82121369],
       [0.8224992 ],
       [0.82223124],
       [0.81865563],
       [0.81898508],
       [0.82310224],
       [0.82380692],
       [0.82507372],
       [0.81963911],
       [0.82058682],
       [0.82373265],
       [0.82121572],
       [0.81533976],
       [0.82174247],
       [0.82150007],
       [0.81244887],
       [0.81619789],
       [0.82150007],
       [0.82275702],
       [0.81859688],
       [0.82275702],
       [0.817